### ISSUE TITLE
Workflow repository

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/spatial-hub#194]
Annotations and SP Workflow repository ID to be captured in Metadata.

**Comment by Tasilee** [comment]
WORKFLOW REPOSITORY

1. The test sequence works perfectly. Very neat indeed!
1.  Name of workflow needs to be editable
1. Current default name is variant of 'Created' ISO date-time...suggest it should be the same ISO date-time string by default rather than reversing date sequence.  Adding an ID# such as '436' fine
1. Name of Workflow pop-up window should be 'Your Workflows'? This makes me wonder about sharing workflows. Can you import a workflow from someone else, which presumes an export I guess (or copy/paste?
1. When I click on Workflows (top/right), and the workflow window appears, I have two workflows 'current session' and '436' but there is a Save and Run button - so what will those apply to? It isn't obvious.
1. If I click Load on the 436 workflow, I get three columns. Type and Action make sense but should it be 'Parameters' rather than 'Annotation' as that is what it looks like to me? At this point I am thinking maybe I could add an annotation outside the braces? If I try this, it replaces what is in the box and this won't work unless you reproduce the formatting. So it doesn't look like an annotation to me.
1. If I click on 'edit' against environmental layer, I get the layer selection window, which I wasn't expecting, but I understand why. 
1. If I click on a new layer in the layer selection window, the 'annotation' doesn't change as expected.
1. If I Save the workflow and then Open Workflows again, I have another '436' with the same name as the other 436 (not good) but with the current date-time. I presume a duplicate. Looks like it if I examine and run both.
1. I delete existing layers and run a sequence of adding a species, an area, an environmental layer then filtering the species on  Bio17 (all nice). Then I Load the current session, rename it and Save it and get '437' rather than my new name.
1. I remove all the mapped layers, click on Workflows and Load my renamed workflow, all good. There are 14 steps! Yikes, more than I expected. I run the workflow and get the original one and my  new sequence - which I didn't expect.  Now I see why there are 14 steps.
1. I edit my workflow to remove first 10 steps, leaving the obvious 4 I thought I had. All good, but what is the 'Skip annotation' thing at the bottom?
1. Why no 'Save' on edired workflow?
1. I Run the workflow. First 3 steps are quick but filtering step takes minutes....locks up it seems.

**Comment by Tasilee** [comment]
1. Confusion between 'Load" and "Workflows". Why not just use a single command "Workflows" where you can 1) List, 2) Load and 3) Save a workflow or "Session"? This then raises what the difference is between a 'snapshot' of a session and workflow that will (re-) generate that session
1. Default workflow name e.g., "My workflow 10/16/2019, 9:37:37 AM" uses USA date - confusing. I'd suggest default shortened to " (ID?) Date Time"
1. I don't see why a Load of current workflow allows a rename and save while the Load of another workflow only allows Run?
1. "Workflow" and "Load" does allow for a "Save"? The pop-up window is titled "Run workflow", but surely an edit and save is appropriate?
1. It isn't obvious to me if/how you can edit a workflow beyond deleting a step.
1, If a workflow produces a filtered layer, the name of the layer is anomalous, as in "Species layer - Facet (invalidScientificName /invalidScientificName /invalidScientificName /invalidScientificName /invalidScientificName /invalidScientificName )". This was captured via (i) on the layer. Suggest this should include the filters applied - which I presume was the intent.
1. Load (workflow) doesn't reflect a Saved edit and renamed workflow. "Workflow" does.
1. My workflow (mistakenly) had a step for looking at the species info (clicking on (i) to see what the filters were), and this seemed to generate multiple pop-up windows (at least 12) and slowed/stopped the workflow (red bar hovering). It would have been useful to be able to copy (or export as text), the parameters of the Actions/steps to archive the workflow or, as here, document an issue. I couldn't copy/paste the Parameters/annotations. See "Lee workflow 10/16/2019, 9:53:18 AM".
1. If I do "Workflows", "Load" the above one, remove a step/Action and either Save or Run, the 'edited' workflow is not saved: The removed step re-appears. 
![Filter](https://user-images.githubusercontent.com/6656350/66876488-b55c4c00-effd-11e9-9a07-d764b2b0e274.jpg)
![Workflow1](https://user-images.githubusercontent.com/6656350/66876493-b8efd300-effd-11e9-806a-7f418d5772d6.jpg)
