### ISSUE TITLE
DOI storage to be made searchable

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/spatial-hub#215]
Belongs to #179

**Comment by chrisala** [comment]
This has been implemented using the grails elasticsearch plugin, the latest version of which requires elasticsearch 5.4.3.

It's currently using an embedded elasticsearch instance (local transport) due to it being non-trivial to configure elasticsearch 5.4.3 with ansible.  (Our current ansible setup is using es 1.x and the offical es ansible scripts only support 6.x & 7.x).

**Comment by chrisala** [comment]
See https://github.com/AtlasOfLivingAustralia/doi-service/issues/46

**Comment by ansell** [comment]
It could be useful to contribute an update to the elasticsearch grails plugin to either go to 5.6.16 or 7.2.0, as 5.4.3 is a very old release (2 years old) and we can't support it ourselves to keep the essential doi service running.

The DOI storage also contains sensitive non-public data, so any searching on it needs to also include authentication and permission checking and never return results if the authenticated user does not have access to the DOI in question.

All DOI's are also getting PUBLIC_READ permissions on S3, which also needs to be fixed before any search interface is deployed https://github.com/AtlasOfLivingAustralia/doi-service/issues/45

Tracking DOI issues in the doi-service tracker is also ideal, rather than tracking them here.
