### ISSUE TITLE
Export map option is gone, will it be reinstated?

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#244]
Support ticket asks about this https://support.ehelp.edu.au/a/tickets/37353

> I try to download it by clicking on 'export' there is no 'map' option or 'download' option as mentioned on your help page

Please advise if this will be reverted or not?

**Comment by Tasilee** [comment]
We have had at least 3 tickets on this which I have answered. 

The option was removed as it lacked detail due to not hosting basemaps and no legend and given you can do better right now with PC and Mac screen captures, we removed the options.. @adam-collins Said we now host OpenStreetmaps but we still have work on a legend to be done with a priority lower than most current bugs and CSDM project.

**Comment by ansell** [comment]
The documentation should be updated not to refer to the function, and more generally updated to match the current interface.

**Comment by timhicks-ala** [comment]
Additionally mentioned here: https://support.ehelp.edu.au/a/tickets/95175
