### ISSUE TITLE
Clicking "Next" before closing polygon breaks New area process

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#343]
- Add to map -> Area -> Draw polygon -> Next
- Start drawing a polygon, but do not click the first point again - do not complete the polygon
- It is possible to click "Next" and have a progress bar appear, but it will never complete as the polygon is not complete and the WKT text has not been generated.

Solution: Disable the "Next" button on the "Create area" dialog until the polygon is completely drawn and closed.

![SP open polygon](https://user-images.githubusercontent.com/57081387/92672548-477aea80-f35c-11ea-95da-c1043057f60c.png)

**Comment by nickdos** [comment]
@adam-collins add commit link

**Comment by qifeng-bai** [comment]
Draw points, circus or other 'drawing on map' will cause this issue. Mainly because :  
ng-disabled="(intersect.value.length == 0 && selectedArea.wkt.length == 0)"

Either  Intersect or selectedArea will be null,  so it always return false

PR:  https://github.com/AtlasOfLivingAustralia/spatial-hub/pull/360

NOTE: not sure why this PR contains another PR of QID
