### ISSUE TITLE
Add configurable notification banner

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/spatial-hub#357]
As an ALA admin I would like to be able to put a notification banner on a spatial hub instance.  This banner could be used to warn users they are viewing a non-production system, that there will be upcoming system maintenance etc.

The ala-admin plugin, which is integrated into spatial-hub, provides a similar facility but the message set in `alaAdmin` does not show on the main spatial hub interface.

**Comment by adam-collins** [comment]
Testing. Admin page is working. Setting a message works. Clearing message works. Message type works. 

However unless the message is along the lines of "spatial hub is not working" it should not be used. This is because the message cannot be dismissed/closed/hidden and the layout is a bit messed up.
