### ISSUE TITLE
Scatterplot not generating 

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/spatial-hub#439]
Support ticket #146501 

User reported error generating a scatterplot, please see below:

"I am trying to use the spatial portal to develop climatic envelopes for threatened hibiscus species growing on islands in Indian and Pacific Oceans (including Vanuatu, Fiji, Hawaii, Madagascar and Mauritius). For output I got the attached scatterplot...can you tell me what this means?"

![spatial-error-scatterplot](https://user-images.githubusercontent.com/90439797/164116085-a6eec8ee-cfe8-412a-8fec-3ba34170b112.jpg)

reported by Dr Lex Thomson

**Comment by qifeng-bai** [comment]
That is the task: https://spatial.ala.org.au/ws/tasks/show/1805360

**Comment by qifeng-bai** [comment]
Reason of this issue is:
The scatterplot tried to compute Hibiscus arnottianus species against all species (as background) over the world.  

It is too heavy for Spatial and Biocache, so the task was killed, and another consequence was Spatial server has high CPU load. 

See task details: https://spatial.ala.org.au/ws/tasks/show/1805360
