### ISSUE TITLE
Unable to import points from CSV by any method

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/spatial-hub#445]
No longer able to import points using a CSV file, which previously worked.

Trying to upload a CSV file, the following error message appears:
“There are errors in the dataset that needs to be fixed before you can upload.”

It is possible to upload points using the paste CSV function, either from Spatial or starting from ALA Sandbox and moving across to SP.

---

*update 25/11/22* I'm aware this is a deprecated feature now, but believe it was still meant to work using the 'paste CSV' function, and/or by using ALA Sandbox. I found that the upload stopped at 25% for all 4 methods. 

Given that our users find this feature useful in their work, could we please aim to fix so that at least one of the methods to import points from CSV works?

Raised by user: https://support.ehelp.edu.au/a/tickets/156585

**Comment by kylie-m** [comment]
Raised by a second user: https://support.ehelp.edu.au/a/tickets/162977

**Comment by timhicks-ala** [comment]
Additionally raised in https://support.ehelp.edu.au/a/tickets/166570

**Comment by timhicks-ala** [comment]
Some investigation. It appears impossible to use the Import -> Points tool in Spatial, which means it's impossible to run AOO/EOO analysis on uploaded data. Neither uploading a file and pasting CSV data works as in both cases, the process fails at 25%.

![failed at 25percent](https://user-images.githubusercontent.com/57081387/215376783-e2a45ad2-2e1d-47a7-bae6-fe6ba6f72535.png)

Strangely, if you then try and run an AOO/EOO and "Use imported points", the failed uploads will appear in the list. Note that a test CSV with four records in it shows as having 5 occurrences - possibly it's counting the header row as a record here:

![use imported points](https://user-images.githubusercontent.com/57081387/215377236-fa7c4be3-9a20-400e-8d6c-38a2a34b19e2.png)

In either case, the AOO/EOO fails, stating no occurrences were found in the defined area, despite the area having been left as the default World:

![no occurrences found](https://user-images.githubusercontent.com/57081387/215377705-69d47262-7617-41d5-9678-d88b84a92c68.png)

If I attempt to paste just the four lines of CSV with records in them, ignoring the header row, it still fails, but at 50% instead of 25%, and the list of imported points shows an entry with 4 records in it:

![failed at 50percent](https://user-images.githubusercontent.com/57081387/215377824-68780b7b-c048-4a3d-9053-5bd90ec30315.png)

So:
- The process to upload points to Spatial is failing, affecting at least AOO/EOO and any other tools that rely on it
- Despite failing, it still records the upload as successful, in terms of adding that upload to a list of points available
- That list is unusable for some reason

**Comment by sat01a** [comment]
Assigned to @adam-collins

**Comment by adam-collins** [comment]
SOLR was down. Also CSV import is working again for me in Chrome. Pasting data still works.

**Comment by sat01a** [comment]
Closing the issue. @adam-collins confirmed it works
