### ISSUE TITLE
Auto close tool windows when finished

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#76]
Auto close tool windows instead of displaying the 'finished' button.

**Comment by qifeng-bai** [comment]
The finish panel contains status bar and download link.  It provides a direct hint that the task is completed.  We can improve it by changing the blink blue status to a normal color info bar if status is successful

**Comment by Tasilee** [comment]
If there is useful information on the window, then we need to display it. If we are just notifying 'finished' then a 'close' is sufficient? If there are downloads, do we flag them with a download button or just do it? Probably the latter?

**Comment by qifeng-bai** [comment]
![screen shot 2018-05-03 at 9 40 31 am](https://user-images.githubusercontent.com/31238531/39554468-500fcd5c-4eb6-11e8-8cfe-0fbc297d192d.png)
I am using one of tools as an example. The downloading automatically starts after the task is completed. We can see there is a downloaded at the left bottom corner of browser. 
The reason I can found this file is because I saw the status of task is finished, so I looked around to find any outcomes.  I am wondering if the downloaded file would be ignored if no such 'finished' info panel popup?
